services:
  ffmpeg-tool:
    build:
      context: .
    container_name: ffmpeg-real-time-overlay-engine
    command: python app.py --help
    volumes:
      - ./data:/data
      - ./output:/output
      - ./config:/config
    environment:
      PYTHONUNBUFFERED: "1"
